name: Feature Request
description: Suggest a new feature or enhancement for TACo
title: '[Feature]: '
labels: ['enhancement']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: dropdown
    id: app
    attributes:
      label: Which app is this for?
      description: Select the app this feature would be added to
      options:
        - Tenure (Job Search)
        - Tempo (Brain Dump)
        - Paper Trail (News Aggregator)
        - Nurture (Relationship Manager)
        - New App
        - Cross-App (affects multiple apps)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Motivation
      description: Why would this feature be useful? What problem does it solve?
      placeholder: |
        As a [type of user], I want [goal] so that [benefit].

        This would help because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented? (optional)
      placeholder: Describe your proposed solution

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or features? (optional)
      placeholder: Describe alternatives you've considered

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request
      placeholder: Any additional information that might help
